#!/usr/bin/env python3
"""dicebear.py OUT.json PACKAGE_DIR...: avatar styles for the welcome app
(live-welcome), from DiceBear's style packages (@dicebear/<style>).

A DiceBear style is SVG templates in JavaScript, generated by its Figma
exporter: a body with the style's parts in it (hair, eyes, mouth...), parts
that can hold other parts, and colors, each part and color picked from the
schema's defaults, optional parts present with some probability. This turns
them into JSON the app composes itself, offline:

  {"styles": [{"id": "open-peeps", "title": "Open Peeps",
               "creator": "Pablo Stanley", "license": "CC0 1.0",
               "attributes": {"viewBox": "0 0 704 704", ...},
               "body": "<svg markup with %%color:skin%% and %%part:head%%>",
               "parts": {"head": {"afro": "<svg markup>", ...}, ...},
               "choices": {"head": ["afro", ...], ...},
               "probability": {"facialHair": 10, ...},
               "colors": {"skin": ["ffdbb4", ...], ...},
               "backgrounds": [...]}, ...]}

Parts not in "probability" are always there. Any other JavaScript in a
template (a style that computes more than this) makes it fail rather than
guess.
"""
import json
import os
import re
import sys

# ${escape.xml(`${colors.skin}`)}
COLOR = re.compile(r"\$\{escape\.xml\(`\$\{colors\.(\w+)\}`\)\}")
# ${(_b = (_a = components.head) === null || ... .value(components, colors)) ... : ''}
PART = re.compile(r"\$\{\(_\w+ = \(_\w+ = components\.(\w+)\) === null \|\| _\w+ === void 0 \? "
                  r"void 0 : _\w+\.value\(components, colors\)\) !== null && _\w+ !== void 0 "
                  r"\? _\w+ : ''\}")


def js_value(source):
    """A JavaScript object/array literal of plain values, as Python."""
    s = re.sub(r"'((?:[^'\\]|\\.)*)'", lambda m: json.dumps(m[1]), source)
    s = re.sub(r"([{,]\s*)([A-Za-z_$][\w$]*)\s*:", r'\1"\2":', s)
    s = re.sub(r",(\s*[}\]])", r"\1", s)
    return json.loads(s)


def placeholders(js):
    return PART.sub(r"%%part:\1%%", COLOR.sub(r"%%color:\1%%", js))


def fail(style, message):
    sys.exit(f"{style}: {message}")


def components(style, path):
    js = placeholders(open(path).read())
    m = re.search(r"export const (\w+) = \{\n(.*)\n\};", js, re.S)
    if not m:
        fail(style, f"{path}: unexpected format")
    # name: (components, colors) => `...`, or with a body (for the variables
    # of the parts it holds): => { var _a, _b; return `...`; },
    entries = re.findall(r"^    '?(\w+)'?: \(components, colors\) => "
                         r"(?:\{ var [\w, ]+; return )?`(.*?)`(?:; \})?,?$", m[2], re.M)
    if not entries or len(entries) != len(re.findall(r"^    '?\w+'?:", m[2], re.M)):
        fail(style, f"{path}: unexpected format")
    return m[1], dict(entries)


def convert(package):
    lib = f"{package}/lib"
    style = json.load(open(f"{package}/package.json"))["name"].split("/")[-1]
    index = placeholders(open(f"{lib}/index.js").read())
    meta = js_value(re.search(r"export const meta = (\{.*?\n\});", index, re.S)[1])
    attributes = js_value(re.search(r"attributes: (\{.*?\}),\n", index, re.S)[1])
    body = re.search(r"body: `(.*?)`,\n", index, re.S)[1]
    schema = js_value(re.search(r"export const schema = (\{.*\});", open(f"{lib}/schema.js").read(),
                                re.S)[1])["properties"]

    parts = dict(components(style, f"{lib}/components/{name}")
                 for name in sorted(os.listdir(f"{lib}/components"))
                 if name.endswith(".js") and name != "index.js")
    choices, probability, colors = {}, {}, {}
    for group in parts:
        choices[group] = schema.get(group, {}).get("default") or list(parts[group])
        if any(c not in parts[group] for c in choices[group]):
            fail(style, f"{group}: the schema names parts that don't exist")
        if f"{group}Probability" in schema:
            probability[group] = schema[f"{group}Probability"]["default"]
    markup = [body] + [m for group in parts.values() for m in group.values()]
    for name in sorted({c for m in markup for c in re.findall(r"%%color:(\w+)%%", m)}):
        colors[name] = [c for c in schema.get(f"{name}Color", {}).get("default", [])]
        if not colors[name]:
            fail(style, f"no colors for {name}")
    for m in markup:
        if "${" in m or "`" in m:
            fail(style, f"unexpected JavaScript in a template: {m[:80]}")
        for part in re.findall(r"%%part:(\w+)%%", m):
            if part not in parts:
                fail(style, f"unknown part {part}")
    return {
        "id": style, "title": meta["title"], "creator": meta["creator"],
        "license": meta["license"]["name"], "attributes": attributes, "body": body,
        "parts": parts, "choices": choices, "probability": probability, "colors": colors,
        "backgrounds": schema.get("backgroundColor", {}).get("default", []),
    }


def main():
    out, packages = sys.argv[1], sys.argv[2:]
    styles = [convert(p) for p in packages]
    for s in styles:
        if not s["license"].startswith("CC0"):
            sys.exit(f"{s['id']}: {s['license']}, not CC0")
    with open(out, "w") as f:
        json.dump({"styles": styles}, f, separators=(",", ":"))


if __name__ == "__main__":
    main()
